name: cognisync-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - python-dotenv
  - cryptography
  - python-docx
  - pandas
  - whoosh
  - openai
  - faiss-cpu
  - pip
  - pip:
      - pymupdf