name: cognisync-env
channels:
  - conda-forge
  - defaults

dependencies:
  # 基础环境
  - python=3.10.12  # 精确小版本
  - pip=23.3.1

  # Web服务
  - fastapi=0.95.1
  - uvicorn=0.22.0
  - pydantic=2.5.3
  - pydantic-settings=2.0.3

  # 数据处理
  - numpy=1.21.6
  - faiss-cpu=1.7.4

  # NLP模型
  - sentence-transformers=2.2.2
  - transformers=4.25.1
  - huggingface-hub=0.12.0

  # 环境管理
  - python-dotenv=0.21.1
  - openai=0.27.0

  # 文件处理
  - pip:
    - python-docx==0.8.12
    - pymupdf==1.23.6
    - unstructured==0.10.3  # 多格式文本提取增强