name: cognisync-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi=0.95.1
  - uvicorn=0.22.0
  - numpy=1.23.5
  - faiss-cpu=1.7.2
  - sentence-transformers=2.2.2
  - openai=0.27.0
  - python-dotenv=0.21.1
  - pydantic=1.10.2
  - pip
  - pip:
      - python-docx  # 替代 docx 包
      - PyMuPDF      # 替代 fitz 包